apiVersion: v1
kind: Service
metadata:
  namespace: docusaurus
  name: docusaurus-service
spec:
  selector:
    app: docusaurus
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
