apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docusaurus
  name: docusaurus
spec:
  selector:
    matchLabels:
      app: docusaurus
  replicas: 2
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
      - name: docusaurus
        image: vujin/docusaurus:latest
        ports:
        - containerPort: 80
